[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SMTP_HOST = "smtp.163.com"
  SMTP_PORT = "465"
  SMTP_USER = "16690511701@163.com"
  SMTP_FROM = "16690511701@163.com"
  SMTP_FROM_NAME = "AI Hub"
  JWT_SECRET = "aihub-jwt-secret-prod-2026"

[[plugins]]
  package = "@netlify/plugin-nextjs"
